export const SANDBOX_ERROR_CODES = Object.freeze({
  INVALID_REQUEST: "SANDBOX_INVALID_REQUEST",
  UNKNOWN_CAPABILITY: "SANDBOX_UNKNOWN_CAPABILITY",
  UNSUPPORTED_CAPABILITY: "SANDBOX_UNSUPPORTED_CAPABILITY",
  INVALID_HANDLE: "SANDBOX_INVALID_HANDLE",
  NOT_FOUND: "SANDBOX_NOT_FOUND",
  FENCE_MISMATCH: "SANDBOX_FENCE_MISMATCH",
  IDEMPOTENCY_CONFLICT: "SANDBOX_IDEMPOTENCY_CONFLICT",
  INVALID_LIFECYCLE: "SANDBOX_INVALID_LIFECYCLE",
  EXECUTION_NOT_FOUND: "SANDBOX_EXECUTION_NOT_FOUND",
  EXECUTION_TERMINAL: "SANDBOX_EXECUTION_TERMINAL",
  EXECUTION_FENCED: "SANDBOX_EXECUTION_FENCED",
  EXECUTION_INVALID_EVENT: "SANDBOX_EXECUTION_INVALID_EVENT",
  EXECUTION_INVALID_OFFSET: "SANDBOX_EXECUTION_INVALID_OFFSET",
  EXECUTION_OUTPUT_LIMIT: "SANDBOX_EXECUTION_OUTPUT_LIMIT",
  EXECUTION_CANCELLED: "SANDBOX_EXECUTION_CANCELLED",
  EXECUTION_TIMEOUT: "SANDBOX_EXECUTION_TIMEOUT",
  NETWORK_POLICY_INVALID: "SANDBOX_NETWORK_POLICY_INVALID",
  NETWORK_DENIED: "SANDBOX_NETWORK_DENIED",
  NETWORK_RESOLUTION_DENIED: "SANDBOX_NETWORK_RESOLUTION_DENIED",
  NETWORK_REDIRECT_DENIED: "SANDBOX_NETWORK_REDIRECT_DENIED",
  NETWORK_INBOUND_DENIED: "SANDBOX_NETWORK_INBOUND_DENIED",
  LIFECYCLE_POLICY_INVALID: "SANDBOX_LIFECYCLE_POLICY_INVALID",
  LINEAGE_NOT_FOUND: "SANDBOX_LINEAGE_NOT_FOUND",
  LINEAGE_BUSY: "SANDBOX_LINEAGE_BUSY",
  LINEAGE_FENCE_MISMATCH: "SANDBOX_LINEAGE_FENCE_MISMATCH",
  LINEAGE_REVOKED: "SANDBOX_LINEAGE_REVOKED",
  LINEAGE_TREE_DIGEST_MISMATCH: "SANDBOX_LINEAGE_TREE_DIGEST_MISMATCH",
  LINEAGE_RETENTION_EXPIRED: "SANDBOX_LINEAGE_RETENTION_EXPIRED",
  LINEAGE_RETAINED_SECRET: "SANDBOX_LINEAGE_RETAINED_SECRET",
  EPHEMERAL_RETAINED: "SANDBOX_EPHEMERAL_RETAINED",
  ALREADY_DESTROYED: "SANDBOX_ALREADY_DESTROYED",
  SECRET_VALUE: "SANDBOX_SECRET_VALUE",
});

export class SandboxProviderError extends Error {
  constructor(code, detail, path = "$") {
    super(detail);
    this.name = "SandboxProviderError";
    this.code = code;
    this.detail = detail;
    this.path = path;
  }

  toJSON() {
    return {
      code: this.code,
      name: this.name,
      path: this.path,
      detail: this.detail,
    };
  }
}

export function sandboxError(code, detail, path) {
  return new SandboxProviderError(code, detail, path);
}
