export const CREDENTIAL_BROKER_ERROR_CODES = Object.freeze({
  INVALID_SECRET_REF: "CREDENTIAL_BROKER_INVALID_SECRET_REF",
  INVALID_BINDING: "CREDENTIAL_BROKER_INVALID_BINDING",
  INVALID_CAPABILITY: "CREDENTIAL_BROKER_INVALID_CAPABILITY",
  CAPABILITY_EXPIRED: "CREDENTIAL_BROKER_CAPABILITY_EXPIRED",
  CAPABILITY_REVOKED: "CREDENTIAL_BROKER_CAPABILITY_REVOKED",
  CAPABILITY_REPLAYED: "CREDENTIAL_BROKER_CAPABILITY_REPLAYED",
  CAPABILITY_BINDING_MISMATCH: "CREDENTIAL_BROKER_CAPABILITY_BINDING_MISMATCH",
  CAPABILITY_REQUEST_MISMATCH: "CREDENTIAL_BROKER_CAPABILITY_REQUEST_MISMATCH",
  CAPABILITY_NOT_FOUND: "CREDENTIAL_BROKER_CAPABILITY_NOT_FOUND",
  PROVIDER_HANDSHAKE_REQUIRED: "CREDENTIAL_BROKER_PROVIDER_HANDSHAKE_REQUIRED",
  PROVIDER_UNSUPPORTED: "CREDENTIAL_BROKER_PROVIDER_UNSUPPORTED",
  PROVIDER_MODE_MISMATCH: "CREDENTIAL_BROKER_PROVIDER_MODE_MISMATCH",
  PROVIDER_ATTESTATION_INVALID:
    "CREDENTIAL_BROKER_PROVIDER_ATTESTATION_INVALID",
  LOCAL_PROVIDER_IN_PRODUCTION:
    "CREDENTIAL_BROKER_LOCAL_PROVIDER_IN_PRODUCTION",
  PROVIDER_REQUEST_FAILED: "CREDENTIAL_BROKER_PROVIDER_REQUEST_FAILED",
  PROVIDER_RESPONSE_INVALID: "CREDENTIAL_BROKER_PROVIDER_RESPONSE_INVALID",
  SECRET_NOT_FOUND: "CREDENTIAL_BROKER_SECRET_NOT_FOUND",
  CONSUMER_REQUIRED: "CREDENTIAL_BROKER_CONSUMER_REQUIRED",
  CONSUMER_OUTPUT_LEAK: "CREDENTIAL_BROKER_CONSUMER_OUTPUT_LEAK",
  INVALID_REQUEST: "CREDENTIAL_BROKER_INVALID_REQUEST",
});

export class CredentialBrokerError extends Error {
  constructor(code, message, details = undefined, options = undefined) {
    super(message, options);
    this.name = "CredentialBrokerError";
    this.code = code;
    if (details !== undefined) this.details = details;
  }
}

export function credentialBrokerError(
  code,
  message,
  details = undefined,
  options = undefined,
) {
  return new CredentialBrokerError(code, message, details, options);
}
